routes:
  - path_prefix: /api/recieve
    backend: recieve
  - path_prefix: /api/buy
    backend: buy
  - path_prefix: /api/payments
    backend: payments
  - path_prefix: /api/orders
    backend: orders

default_response:
  body: “This is not reachable”
  status_code: 403

backends:
  - name: recieve
    match_labels:
      - app_name=recieve
      - env=production
  - name: buy
    match_labels:
      - app_name=buy
      - env=production
  - name: payments
    match_labels:
      - app_name=payments
      - env=production
  - name: orders
    match_labels:
      - app_name=orders
      - env=production
