services:
  buy:
    container_name: buy-service
    hostname: buy-service
    image: amit894/buy:1.0.0
    labels:
    - app_name=buy
    - env=production
    ports:
    - 81:80
  orders:
    container_name: orders-service
    hostname: orders-service
    image: amit894/orders:1.0.0
    labels:
    - app_name=orders
    - env=production
    ports:
    - 83:80
  payments:
    container_name: payments-service
    hostname: payments-service
    image: amit894/payments:1.0.0
    labels:
    - app_name=payments
    - env=production
    ports:
    - 82:80
  recieve:
    container_name: recieve-service
    hostname: recieve-service
    image: amit894/recieve:1.0.0
    labels:
    - app_name=recieve
    - env=production
    ports:
    - 80:80
version: '3'
