services:
  buy:
    image: amit894/buy:1.0.0
    ports:
    - 81:80
  orders:
    image: amit894/orders:1.0.0
    ports:
    - 83:80
  payments:
    image: amit894/payments:1.0.0
    ports:
    - 82:80
  recieve:
    image: amit894/recieve:1.0.0
    ports:
    - 80:80
version: '3'
